#!/bin/zsh

########################################
# Custom Functions

function reprobe()
{
    for arg in "${*[@]}"; do
        sudo modprobe -r $arg
        sudo modprobe $arg
    done
}

# Use this to manage daemons
function service()
{
    sudo /etc/rc.d/$@
}

# Other stuff that i should use more often
function goto() { [ -d "$1" ] && cd "$1" || cd "$(dirname "$1")"; }
function cpf() { cp "$@" && goto "$_"; }
function mvf() { mv "$@" && goto "$_"; }

function rs() { rsync -auvhP "$@" }
function touchee() { touch $2 && chmod $1 $2 }
function md() { mkdir -p "$@" && cd "$1" }

function testarchive() { 7za l "$@" }

function chmview() { wine hh.exe `winepath -w $1` }

CRYPT_EXT='3des'
function encrypt() {
        [ -e "$1" ] || return 1
        openssl des3 -salt -in "$1" -out "$1.$CRYPT_EXT"
        [ -e "$1.$CRYPT_EXT" ] && shred -u "$1"
}
function decrypt() {
        [ -e "$1" ] || return 1
        [ "${1%.$CRYPT_EXT}" != "$1" ] || return 2
        openssl des3 -d -salt -in $1 -out ${1%.$CRYPT_EXT}
        [ -e "${1%.$CRYPT_EXT}" ] && rm -f "$1"
}

confirm() {
    local answer
    echo -ne "zsh: sure you want to run '${YELLOW}$@${NC}' [yN]? "
    read -q answer
    if [[ "${answer}" =~ ^[Yy]$ ]]; then
        echo
        command "${=@}"
    elif [[ "${answer}" =~ ^[Nn]$ ]]; then
        echo
    fi
}

poweroff() {
    local runcommand
    if [ -n "${USER}" ] && [ "${USER}" != 'root' ]; then
        runcommand="sudo poweroff"
    else
        runcommand='poweroff'
    fi
    confirm "${runcommand}" "$@"
}

reboot() {
    local runcommand
    if [ -n "${USER}" ] && [ "${USER}" != 'root' ]; then
        runcommand='sudo reboot'
    else
        runcommand='reboot'
    fi
    confirm "${runcommand}" "$@"
}

downall()
{
    wget -r -l1 -H -t1 -nd -N -np -A.mp3 -erobots=off -i "$1"
}
